name: dapr_proto
description: An assiting package for dapr_client package.
version: 0.0.3

homepage: https://abhilash-chandran.com
repository: https://github.com/Abhilash-Chandran/dart-sdk

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  protobuf: ^2.0.0   
  grpc: ^3.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
