apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-local
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: components/local_secrets.json
    - name: nestedSeparator
      value: ":"
