name: dapr_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'

# Temporary to keep the analyzer happy.
# Remove it once the packages are published.
publish_to: none

dependencies:
  http: ^0.13.4  
  grpc: ^3.0.2
  dapr_proto: ^0.0.3
  dapr_common: 
    path: ../dapr_common

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dapr_server: 
    path: ../dapr_server
  mockito: ^5.0.16