// Mocks generated by Mockito 5.0.16 from annotations
// in dapr_common/src/mocks/http_mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dapr_common/dapr_common.dart' as _i2;
import 'package:dapr_common/src/mocks/http_mocks.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePubSubResponse_0 extends _i1.Fake implements _i2.PubSubResponse {}

/// A class which mocks [TestPubSub].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestPubSub extends _i1.Mock implements _i3.TestPubSub {
  MockTestPubSub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PubSubResponse> testCallBack(dynamic data) =>
      (super.noSuchMethod(Invocation.method(#testCallBack, [data]),
              returnValue:
                  Future<_i2.PubSubResponse>.value(_FakePubSubResponse_0()))
          as _i4.Future<_i2.PubSubResponse>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TestBinding].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestBinding extends _i1.Mock implements _i3.TestBinding {
  MockTestBinding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> testCallBack(_i2.BindingEvent? bindingEvent) =>
      (super.noSuchMethod(Invocation.method(#testCallBack, [bindingEvent]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  String toString() => super.toString();
}
