name: service_invoker
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  dapr_server:
    path: "../../"
  dapr_client:
    path: "../../../dapr_client"

dev_dependencies:
  lints: ^1.0.0
